name: lingola_buddy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.1
  flutter_svg: ^2.2.0
  dio: ^5.9.0
  flutter_tts: ^4.2.5
  url_launcher: ^6.3.2
  record: ^6.2.0
  path_provider: ^2.1.5
  image_picker: ^1.2.2
  file_picker: ^11.0.2
  path: ^1.9.1
  shared_preferences: ^2.5.5
  permission_handler: ^12.0.1
  audioplayers: ^6.6.0
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
  image_path: assets/images/app_launcher_icon.png
  adaptive_icon_background: "#7429FF"
  adaptive_icon_foreground: assets/images/app_launcher_icon.png
  remove_alpha_ios: true

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/
    - assets/translations/

